name: Notify Discord on Push
on:
  push:
    branches:
      - main  # This will trigger the workflow on pushes to the main branch. Adjust as needed.

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Customize your message with JSON
          curl -X POST -H "Content-Type: application/json" \
          -d '{"username": "GitHub Bot", "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "content": "**New Commit on Main Branch**\n**Message:** '${{ github.event.head_commit.message }}'\n**Author:** '${{ github.event.head_commit.author.name }}'\n**URL:** '${{ github.event.head_commit.url }}'"}' \
          $DISCORD_WEBHOOK
